#!/bin/sh
#
# Assume there is a tmux window named vim that has a vim instance
# in pane 1 and use it as the editor.
# If the assumptions above fail fall back to just starting up a
# vim instance.

# make sure we're inside a tmux session
if [ x"$TMUX_PANE" = x ]; then
  vi -X "$1"
fi

if $(tmux list-windows |grep -q '^1:\ vim'); then
  if [ x"$1" != x ]; then
    FILENAME=$(echo $1 | sed 's/\ /\\ /g')
    DIRECTORY=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
    tmux send -t :vim.1 ":cd $DIRECTORY | e $FILENAME" C-m;
  fi;
  tmux select-window -t :vim \; select-pane -t :.1;
  echo "[hit ENTER when ready]"
  read
else
  vi -X "$1"
fi
